# Generated by Django 5.1.7 on 2025-06-26 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="profile_picture",
            field=models.URLField(blank=True, null=True),
        ),
    ]
