# Generated by Django 5.1.7 on 2025-09-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_customuser_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("admin", "Admin"),
                    ("data_manager", "Data Manager"),
                    ("director", "Director"),
                ],
                default="user",
                max_length=20,
                verbose_name="Role/User Type",
            ),
        ),
    ]
